### ISSUE TITLE
Add sample React module 

### ISSUE THREAD

**Issue by bran-van-d** [HubSpot/cms-sample-assets#4]
## Description
[Link to cms-react repo](https://github.com/HubSpot/cms-react)

We plan on having a CLI command that allows us to create a boilerplate default React module. [We have some code as an example in our SampleReactModule](https://git.hubteam.com/HubSpot/web-default-modules/tree/master/src/jsr-modules/src/components/modules/SampleJSR-V0) (still called SampleJSR,  but we'll rename soon), which is a good example of the basics to get started. 

It allows the user to see what they're working with and how everything is setup. Let me know if you think it should be even more barebones though.

**Comment by TanyaScales** [comment]
This is complete - module was added in the repo here: https://github.com/HubSpot/cms-sample-assets/tree/main/modules/SampleReactModule
